---
grails:
    profile: web
    codegen:
        defaultPackage: grailsplugins
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    jmx:
        unique-names: true
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
management:
    endpoints:
        enabled-by-default: true
    info:
        git:
            enabled: true
            mode: simple
---
grails:
    plugins:
        blacklist:
            - grails-navigation-core
            - grails-navigation
    assets:
        babel:
            enabled: true
        cors:
            enabled: true
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none

twitter:
    enabled: true
    consumerKey: ${GP_TWITTER_CONSUMER_KEY}
    consumerSecret: ${GP_TWITTER_CONSUMER_SECRET}
    accessToken: ${GP_TWITTER_ACCESS_TOKEN}
    accessTokenSecret: ${GP_TWITTER_ACCESS_TOKEN_SECRET}
github:
    username: ${GP_GITHUB_USERNAME}
    token: ${GP_GITHUB_TOKEN}
bintray:
    username: ${GP_BINTRAY_USERNAME}
    token: ${GP_BINTRAY_TOKEN}
---
com:
    grails:
        plugins:
            refresh:
                enabled: true
---
environments:
    development:
        grails.serverURL: http://localhost:8080
    production:
        com.grails.plugins.refresh.enabled: false
        grails.serverURL: https://plugins.grails.org
---
micronaut:
    http:
        client:
            read-timeout: 15s
